name: Node.js Addon with CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
      fail-fast: false

    steps:
    # Checkout repo and submodules
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Cache CMake build files
    - name: Cache CMake build
      uses: actions/cache@v4
      with:
        path: |
          build
          ~/.cmake
        key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt', 'abieos/**') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Build native module
    - name: Build Linux native module
      run: npm run build:linux

    # Build TypeScript
    - name: Build TypeScript
      run: npm run build

    # Run tests
    - name: Run tests
      run: npm test

    - name: Run coverage tests
      if: matrix.node-version == '22.x'
      run: npm run test:coverage

    - name: Upload coverage to Coveralls
      if: matrix.node-version == '22.x'
      uses: coverallsapp/github-action@v2
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # Upload build artifacts on failure for debugging
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-node-${{ matrix.node-version }}
        path: |
          build/**/*.log
          npm-debug.log*
        if-no-files-found: ignore
